version: "3.9"
services:
  # pgbouncer:
  #   image: edoburu/pgbouncer:latest
  #   ports:
  #     - "6432:6432" # PgBouncer listening port
  #   env_file: .pgbouncer.dev.env
  #   environment:
  #     # PgBouncer settings, adjust according to your needs
  #     POOL_MODE: transaction
  #     # AUTH_TYPE: scram-sha-256
  #     LISTEN_PORT: 6432
  #   networks: 
  #     - khoj
      
  server:
    # depends_on: 
    #   - pgbouncer
    # Use the following line to use the latest version of khoj. Otherwise, it will build from source.
    # image: ghcr.io/khoj-ai/khoj:latest
    # Uncomment the following line to build from source. This will take a few minutes. Comment the next two lines out if you want to use the offiicial image.
    build:
      context: .
    ports:
      # If changing the local port (left hand side), no other changes required.
      # If changing the remote port (right hand side),
      #   change the port in the args in the build section,
      #   as well as the port in the command section to match
      - "42110:42110"
    working_dir: /app
    volumes:
      - khoj_config:/root/.khoj/
      - khoj_models:/root/.cache/torch/sentence_transformers
    # Use 0.0.0.0 to explicitly set the host ip for the service on the container. https://pythonspeed.com/articles/docker-connection-refused/
    environment:
      - ENV_VERSION=dev
    env_file: .env
    command: --host="0.0.0.0" --port=42110 -vv --anonymous-mode
    networks: 
      - khoj

networks:
  khoj:
 
volumes:
  khoj_config:
  khoj_models:
