version: "3.9"
services:
  pgbouncer:
    image: edoburu/pgbouncer:latest
    ports:
      - "6432:6432" # PgBouncer listening port
    env_file: .pgbouncer.test.env
    networks:
      - default
      
  server:
    # Use the following line to use the latest version of khoj. Otherwise, it will build from source.
    # image: ghcr.io/khoj-ai/khoj:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42110:42110"
    working_dir: /app
    volumes:
      - khoj_config:/root/.khoj/
      - khoj_models:/root/.cache/torch/sentence_transformers
    env_file: .env
    environment:
      # Important variable: env version
      - ENV_VERSION=test.pgbouncer
      - port=42110
    command: --host="0.0.0.0" --port=42110 -vv --anonymous-mode
    # depends_on:
    #   - pgbouncer
    networks:
      - default

networks:
  default:

volumes:
  khoj_config:
  khoj_models:
