version: "3.9"
services:
  server:
    # Use the following line to use the latest version of khoj. Otherwise, it will build from source.
    # image: ghcr.io/khoj-ai/khoj:latest
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "42110:42110"
    working_dir: /app
    volumes:
      - khoj_config:/root/.khoj/
      - khoj_models:/root/.cache/torch/sentence_transformers
    env_file: .env
    environment:
      ENV_VERSION: prod
      port: 42110
    depends_on:
      - pgbouncer
    networks:
      - khoj
      
  pgbouncer:
    image: edoburu/pgbouncer:latest
    ports:
      - "6432:6432" # PgBouncer listening port
    env_file: .pgbouncer.prod.env
    environment:
      # PgBouncer settings, adjust according to your needs
      POOL_MODE: transaction
      AUTH_TYPE: scram-sha-256
      LISTEN_PORT: 6432
    networks:
      - khoj

networks:
  khoj:

volumes:
  khoj_config:
  khoj_models:
